<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo $cedente; ?></title>
    <style type="text/css">

        @media print {
            .noprint {
                display:none;
            }
        }

        body{
            background-color: #ffffff;
            margin-right: 0;
        }

        .table-boleto {
            font: 9px Arial;
            width: 666px;
        }

        .table-boleto td {
            border-left: 1px solid #000;
            border-top: 1px solid #000;
        }

        .table-boleto td:last-child {
            border-right: 1px solid #000;
        }

        .table-boleto .titulo {
            color: #000033;
        }

        .linha-pontilhada {
            color: #000033;
            font: 9px Arial;
            width: 100%;
            border-bottom: 1px dashed #000;
            text-align: right;
            margin-bottom: 10px;
        }

        .table-boleto .conteudo {
            font: bold 10px Arial;
            height: 11.5px;
        }

        .table-boleto .sacador {
            display: inline;
            margin-left: 5px;
        }

        .table-boleto td {
            padding: 1px 4px;
        }

        .table-boleto .noleftborder {
            border-left: none !important;
        }

        .table-boleto .notopborder {
            border-top: none !important;
        }

        .table-boleto .norightborder {
            border-right: none !important;
        }

        .table-boleto .noborder {
            border: none !important;
        }

        .table-boleto .bottomborder {
            border-bottom: 1px solid #000 !important;
        }

        .table-boleto .rtl {
            text-align: right;
        }

        .table-boleto .logobanco {
            display: inline-block;
            max-width: 150px;
        }

        .table-boleto .logocontainer {
            width: 250px;
            display: inline-block;
        }

        .table-boleto .logobanco img {
            margin-bottom: -5px;
            height: 27px;
        }

        .table-boleto .codbanco {
            font: bold 20px Arial;
            padding: 1px 5px;
            display: inline;
            border-left: 2px solid #000;
            border-right: 2px solid #000;
            width: 51px;
            margin-left: 25px;
        }

        .table-boleto .linha-digitavel {
            font: bold 14px Arial;
            display: inline-block;
            width: 406px;
            text-align: right; 
            padding: 2px;   
        }

        .table-boleto .nopadding {
            padding: 0px !important;
        }

        .table-boleto .caixa-gray-bg {
            font-weight: bold;
            background: #ccc;
        }

        img {
            margin-bottom: -5px;
        }
        .table-qrcode {
            width: 100%; /* Defina a largura total da tabela */
            border-collapse: collapse; /* Remova as bordas entre as células */
        }
        .instrucao {
            /* Defina a largura da coluna da instrução */
            width: 100%;
            white-space: nowrap; /* Impede a quebra de linha */    
        }
        .td {
            vertical-align: top; /* Alinha todas as células no topo */
        }
        .qrcode img {
            max-width: 100%; /* Faça a imagem responsiva dentro da célula do Qrcode */
            height: auto;
        }
        .info {
            font: 9px Arial;    
        }

        .info-empresa {
            font: 11px Arial;
        }

        .header {
            font: bold 13px Arial;
            display: block;
            margin: 4px;
        }

        .barcode {
            height: 50px;
        }

        .barcode div {
            display: inline-block;
            height: 100%;
        }

        .barcode .black {
            border-color: #000;
            border-left-style: solid;
            width: 0px;
        }

        .barcode .white {
            background: #fff;
        }

        .barcode .thin.black {
            border-left-width: 1px;
        }

        .barcode .large.black {
            border-left-width: 3px;
        }

        .barcode .thin.white {
            width: 1px;
        }

        .barcode .large.white {
            width: 3px;
        }

        .float_left{
            float:left;
        }

        .center {
            text-align: center;
        }

        .conteudo.cpf_cnpj{
            float:right;
            width:24%;
        }

    </style>
</head>
<body>
    <div style="width: 666px">
        <div class="noprint info">
            <div class="info-qrcode" >
                <table class="table-qrcode" cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                    <tr>
                        <td valign="bottom" colspan="8" class="td-instrucao">
                            <div class="instrucao">
                                <h2>Instruções de Impressão</h2>                   
                                <ul>
                                    <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
                                    <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                                    <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
                                    <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                                    <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
                                </ul>
                            </div>                        
                        </td>
                        <td valign="bottom" class="td-qrcode">
                                <?php if ($qrcode) : ?>
                                <div class="qrcode">
                                    <h2>Qrcode</h2> 
                                    <img alt="qrcode" src="<?php echo $qrcode; ?>" width="70" height="70"/>
                                </div>            
                                <?php endif ?>                        
                        </td>
                    </tr>
                </table> 
            </div> 
            <span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
            <?php if ($valor_documento) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
            <?php if ($pagamento_minimo) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
            <br>
            <div class="linha-pontilhada" style="margin-bottom: 20px;">Recibo do sacado</div>
        </div>

        <div class="info-empresa">
            <?php if ($logotipo) : ?>
            <div style="display: inline-block;">
                <img alt="logotipo" src="<?php echo $logotipo; ?>" />
            </div>
            <?php endif ?>
            <div style="display: inline-block; vertical-align: super;">
                <div><strong><?php echo $cedente; ?></strong></div>
                <div><?php echo $cedente_cpf_cnpj; ?></div>
                <div><?php echo $cedente_endereco1; ?></div>
                <div><?php echo $cedente_endereco2; ?></div>
            </div>
        </div>
        <br>

        <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
            <tbody>
            <tr>
                <td valign="bottom" colspan="5" class="noborder nopadding">
                    <div class="logocontainer">
                        <div class="logobanco">
                            <img src="<?php echo $resource_path . 'src/images/' . $logo_banco; ?>" alt="logotipo do banco">
                        </div>
                        <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                    </div>
                    <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="2" width="250">
                    <div class="titulo">Cedente</div>
                    <div class="conteudo"><?php echo $cedente ?></div>
                </td>
                <td width="90">
                    <div class="titulo">CPF/CNPJ</div>
                    <div class="conteudo"><?php echo $cedente_cpf_cnpj ?></div>
                </td>
                <td width="120">
                    <div class="titulo">Agência/Código do Cedente</div>
                    <div class="conteudo rtl"><?php echo $agencia_codigo_cedente ?></div>
                </td>
                <td width="110">
                    <div class="titulo">Vencimento</div>
                    <div class="conteudo rtl"><?php echo $data_vencimento ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="3" width="446">
                    <div class="titulo">Sacado</div>
                    <div class="conteudo"><?php echo $sacado ?></div>
                    <div class="conteudo"><?php echo $pagador_cpf_cnpj ?></div>
                    <div class="conteudo"><?php echo $pagador_endereco ?></div>
                    <div class="conteudo"><?php echo $pagador_cidade ?> - <?php echo $pagador_estado ?> - CEP: <?php echo $pagador_cep ?></div>
                </td>
                <td>
                    <div class="titulo" width="110">Nº documento</div>
                    <div class="conteudo rtl"><?php echo $numero_documento ?></div>
                </td>
                <td>
                    <div class="titulo" width="110">Nosso número</div>
                    <div class="conteudo rtl"><?php echo $nosso_numero ?></div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="titulo" width="100">Espécie Doc.</div>
                    <div class="conteudo"><?php echo $especie_doc ?></div>
                </td>
                <td>
                    <div class="titulo" width="100">Aceite</div>
                    <div class="conteudo"><?php echo $aceite ?></div>
                </td>
                <td>
                    <div class="titulo" width="100">Data do documento</div>
                    <div class="conteudo"><?php echo $data_documento ?></div>
                </td>
                <td>
                    <div class="titulo" width="150">Carteira</div>
                    <div class="conteudo rtl"><?php echo $carteira ?></div>
                </td>
                <td>
                    <div class="titulo" width="150">Espécie</div>
                    <div class="conteudo rtl"><?php echo $especie ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="titulo">Data Processamento</div>
                    <div class="conteudo"><?php echo $data_processamento ?></div>
                </td>
                <td>
                    <div class="titulo">(-) Desconto / Abatimento</div>
                    <div class="conteudo rtl"><?php echo $desconto_abatimento ?></div>
                </td>
                <td>
                    <div class="titulo">(-) Outras deduções</div>
                    <div class="conteudo rtl"><?php echo $outras_deducoes ?></div>
                </td>
                <td>
                    <div class="titulo">(=) Valor Documento</div>
                    <div class="conteudo rtl"><?php echo $valor_documento ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <div class="titulo">Demonstrativo</div>
                    <div class="conteudo"><?php echo $demonstrativo[0] ?></div>
                </td>
                <td>
                    <div class="titulo">(+) Mora / Multa</div>
                    <div class="conteudo rtl"></div>
                </td>
                <td>
                    <div class="titulo">(+) Outros acréscimos</div>
                    <div class="conteudo rtl"><?php echo $outros_acrescimos ?></div>
                </td>
                <td>
                    <div class="titulo">(=) Valor cobrado</div>
                    <div class="conteudo rtl"><?php echo $valor_cobrado ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="5"><div style="margin-top: 10px" class="conteudo"><?php echo $demonstrativo[1] ?></div></td>
            </tr>
            <tr>
                <td colspan="5" class="notopborder"><div class="conteudo"><?php echo $demonstrativo[2] ?></div></td>
            </tr>
            <tr>
                <td colspan="5" class="notopborder"><div class="conteudo"><?php echo $demonstrativo[3] ?></div></td>
            </tr>
            <tr>
                <td colspan="5" class="notopborder bottomborder"><div style="margin-bottom: 10px;" class="conteudo"><?php echo $demonstrativo[4] ?></div></td>
            </tr>
            </tbody>
        </table>
        <br>
        <div class="linha-pontilhada">Corte na linha pontilhada</div>
        <br>

        <!-- Ficha de compensação -->
        <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
            <tbody>
            <tr>
                <td valign="bottom" colspan="5" class="noborder nopadding">
                    <div class="logocontainer">
                        <div class="logobanco">
                            <img src="<?php echo $resource_path . 'src/images/' . $logo_banco; ?>" alt="logotipo do banco">
                        </div>
                        <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                    </div>
                    <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="5">
                    <div class="titulo">Local de pagamento</div>
                    <div class="conteudo"><?php echo $local_pagamento ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="titulo">Cedente</div>
                    <div class="conteudo"><?php echo $cedente ?> - <?php echo $cedente_cpf_cnpj ?></div>
                </td>
                <td width="120">
                    <div class="titulo">Vencimento</div>
                    <div class="conteudo rtl"><?php echo $data_vencimento ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="titulo">Agência/Código cedente</div>
                    <div class="conteudo"><?php echo $agencia_codigo_cedente ?></div>
                </td>
                <td>
                    <div class="titulo">Nosso número</div>
                    <div class="conteudo rtl"><?php echo $nosso_numero ?></div>
                </td>
            </tr>
            <tr>
                <td width="110">
                    <div class="titulo">Data documento</div>
                    <div class="conteudo"><?php echo $data_documento ?></div>
                </td>
                <td width="120">
                    <div class="titulo">Número documento</div>
                    <div class="conteudo"><?php echo $numero_documento ?></div>
                </td>
                <td width="100">
                    <div class="titulo">Espécie doc.</div>
                    <div class="conteudo"><?php echo $especie_doc ?></div>
                </td>
                <td width="100">
                    <div class="titulo">Aceite</div>
                    <div class="conteudo"><?php echo $aceite ?></div>
                </td>
                <td>
                    <div class="titulo">Data processamento</div>
                    <div class="conteudo rtl"><?php echo $data_processamento ?></div>
                </td>
            </tr>
            <tr>
                <td width="110">
                    <div class="titulo">Carteira</div>
                    <div class="conteudo"><?php echo $carteira ?></div>
                </td>
                <td width="100">
                    <div class="titulo">Espécie</div>
                    <div class="conteudo"><?php echo $especie ?></div>
                </td>
                <td width="150" colspan="2">
                    <div class="titulo">Quantidade</div>
                    <div class="conteudo"><?php echo $quantidade ?></div>
                </td>
                <td>
                    <div class="titulo">Valor</div>
                    <div class="conteudo rtl"><?php echo $valor_unitario ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="titulo">Instruções de responsabilidade do beneficiário. Qualquer dúvida sobre este boleto, contate o beneficiário</div>
                    <div class="conteudo">
                        <?php foreach ($instrucoes as $instrucao): ?>
                        <div><?php echo $instrucao; ?></div>
                        <?php endforeach; ?>
                    </div>
                </td>
                <td>
                    <div class="titulo">(-) Desconto / Abatimento</div>
                    <div class="conteudo rtl"><?php echo $desconto_abatimento ?></div>
                    <div class="titulo">(-) Outras deduções</div>
                    <div class="conteudo rtl"><?php echo $outras_deducoes ?></div>
                    <div class="titulo">(+) Mora / Multa</div>
                    <div class="conteudo rtl"></div>
                    <div class="titulo">(+) Outros acréscimos</div>
                    <div class="conteudo rtl"><?php echo $outros_acrescimos ?></div>
                    <div class="titulo">(=) Valor cobrado</div>
                    <div class="conteudo rtl"><?php echo $valor_cobrado ?></div>
                </td>
            </tr>
            <tr>
                <td colspan="5" class="lastcell">
                    <div class="titulo">Sacado</div>
                    <div class="conteudo">
                        <?php echo $sacado ?> - CPF/CNPJ: <?php echo $pagador_cpf_cnpj ?><br>
                        <?php echo $pagador_endereco ?><br>
                        <?php echo $pagador_cidade ?> - <?php echo $pagador_estado ?> - CEP: <?php echo $pagador_cep ?>
                    </div>
                    <div class="titulo sacador">Sacador/Avalista</div>
                </td>
            </tr>
            </tbody>
        </table>
        
        <div class="codigo-barras">
            <?php if ($codigo_barras_image): ?>
            <div class="barcode-container">
                <img src="<?php echo $codigo_barras_image; ?>" alt="Código de Barras">
            </div>
            <?php endif; ?>
            <div class="info-texto">Autenticação Mecânica</div>
        </div>
    </div>
</body>
</html>